### PR TITLE
Support for .shader files

### PR DESCRIPTION
**Pull request by citizenmatt**
**Work In Progress - DO NOT MERGE YET**

## Support for .shader files

This PR tracks progress adding language support for [ShaderLab](https://docs.unity3d.com/Manual/SL-Reference.html) format .shader files. It is only intended to support the ShaderLab syntax, and not provide any functionality for the shader fragments (`CGPROGRAM`/`CGINCLUDE`) - we'll see about that later.

- [x] Register .shader file type
- [x] Lexer
- [x] Parser
- [ ] Incremental reparsing (i.e. only reparse changes inside a `{ ... }` block instead of the whole file)
- [x] Syntax highlighting/highlight identifiers
- [x] Folding (for Rider)
- [ ] Declarations/declared elements

This PR will track the foundations for language support, with more interesting features (code completion, references, inspections, naming standards, formatting, etc.) implemented separately.

### CODE REVIEW

**Comment by mortentoo** [comment]
Can you add .cginc to this file list as well? Great to see all the work being put into Rider :)

**Comment by citizenmatt** [comment]
Of course, but it will be part of a separate piece of work. This will support the .shaderlab syntax first, then adding CGINCLUDE/CGPROGRAM and .cginc afterwards.

**Comment by mortentoo** [comment]
Fantastic!

**Comment by orac** [comment]
It seems like development on this PR has ground to a halt somewhat. Since I also want this feature to exist, and I have a little experience writing syntax plug-ins for IDEA, is there something I can do to help you out?

**Comment by IvanPashchenko** [comment]
@orac actually, we are very much going to work on it ASAP — current plan is to get this branch merged with shaderlab syntax support, next we'll go for basic highlighting of `Cg` blocks, and then the code completion.

**Comment by telamonian** [comment]
The `shaderlab` branch seems neat. In fact, I have a couple dozen malfunctioning shaders to debug right now, and I could really use some heavy-duty IDE support. Is there any way I could get a build of the Rider plugin from the `shaderlab` branch or, better yet, instructions on how to build it myself? 

I've already tried building the Rider plugin a number of different ways, but even after sorting out the basic dependencies (Gradle, Visual Studio, dotnet-sdk) I keep running into the same error where I get a bunch of messages of the form:

```
  An error occurred while sending the request.
    Couldn't resolve host name
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://repo.labs.intellij.net/api/nuget/dotnet-build/FindPackagesById()?id='JetBrains.ReSharper.SDK''.
```

I assume `http://repo.labs.intellij.net` is a private Jetbrains dev resource? Is there any way to build the plugin without access to it?

**Comment by citizenmatt** [comment]
Sadly, there's no way to build the Rider plugin right now - the SDK bits are still internal. It's on the list to get them published, but we've not got round to it yet. Also, now that the plugin is bundled with Rider, it's a little tricky to upgrade it separately. The plugin can be built and installed into ReSharper though (basically by dropping the Rider projects from the solution).

But the good news is that we'll have a build out very soon with `.shader` support.

However, it's important to point out that this probably won't help much with your misbehaving shaders. Right now, this branch parses the ShaderLab syntax, but doesn't do anything with the `CGPROGRAM` blocks. It's currently basic syntax and syntax error highlighting, with a little bit of code folding and to-do highlighting, but it is the groundwork to some much more interesting functionality.

**Comment by telamonian** [comment]
Bummer. I'll be looking forward to the new build. Guess I'll have to content myself with some basic [shader syntax highlighting](https://gist.github.com/PhannGor/fe73256b8c5c78a1b236e8c919e3d08d) in the meantime.

Also, don't know if this'll help or not, but if you try building the `shaderlab` branch on OSX or Linux you're likely going to run into some trouble with the `\` character in the 1st line of `resharper-unity/resharper/src/resharper-unity/Psi/ShaderLab/Parsing/Chars.lex`. I ended up having to change it to a `/` on my way to figuring out that a local build was probably impossible.

**Comment by IvanPashchenko** [comment]
@telamonian keyword-based highlighting will also be present in the next build, there will be no need for this .xml :)

> Also, don't know if this'll help or not, but if you try building the shaderlab branch on OSX or Linux you're likely going to run into some trouble with the \ character in the 1st line of resharper-unity/resharper/src/resharper-unity/Psi/ShaderLab/Parsing/Chars.lex. I ended up having to change it to a / on my way to figuring out that a local build was probably impossible.

Yep, I've also encountered it, this is fixed in my branch that includes `shaderlab` and a bunch of other changes that we plan to merge.

Regarding the build — we plan to support building without having access to private repo ASAP, it's just a matter of having the stable SDK - Rider is being developed pretty actively, and having people update their code with each EAP didn't seem like a good idea.

**Pull request merged**
