### PR TITLE
Only set csproj properties if value is higher

### PR DESCRIPTION
**Pull request by citizenmatt**
Makes sure we only set `TargetFrameworkVersion` or `LangVersion` if the version we're setting is higher than what's already there. So if a newer Unity (such as the incremental compiler) sets the framework version to 4.7.1, we won't override it with 4.6. Same with `LangVersion`

### CODE REVIEW

**Comment by van800** [comment]
If the target pack of dot net framework is not installed?

**Comment by citizenmatt** [comment]
What do you mean?

**Comment by van800** [comment]
In the case, when user has some dotnet installed, previously we were trying
to use it, but with your change we will fail to open solution and complain
about missing dotnet, right?

**Comment by citizenmatt** [comment]
Hmm. Yes, I've changed the behaviour here. Previously, we would set the target framework version to the latest installed .NET Framework version (e.g. 4.7) when targeting .net 4 and the oldest installed .NET Framework (e.g. 3.5) when targeting .net 2. 

But only on Windows. On Mac/Linux, we would use the default of 4.6 or 3.5, unless it was overridden by the user. And this means that if the new incremental compiler sets it to 4.7.1, we'd overwrite it and downgrade it.

So yes, with this change, we let Unity or a higher priority plugin decide the target framework version more often, and so it could get it "wrong". But only if it's a higher version than we would set - is this more likely to be installed?

Is this something that would be properly solved if we always used the Unity Mono toolset? Would all versions of Unity ship with a toolset that we could use to correctly load the projects with the correctly referenced target framework version, so we wouldn't have to change it at all? More importantly, is this possible?

(And there's also a bug in this change that would only write out two parts of the version - 4.7 instead of 4.7.1, which is also wrong.)

**Comment by van800** [comment]
@citizenmatt will it help with this?
https://github.com/JetBrains/resharper-unity/issues/490
Can I take this both problems for myself?

**Comment by citizenmatt** [comment]
It didn't start as a fix for that, but I think would sort out the C# 7.2 bit, yes.

This started because I'd seen someone post to a forum or something that Unity would now set C# and target framework version, but we always overwrite it, and I though it would be better if we only changed it if it was actually wrong or missing, so we don't have to duplicate Unity logic.

Feel free to take this over.

**Comment by van800** [comment]
close in favor of #506

**Pull request closed without merging**
