### PR TITLE
YAML performance fixes

### PR DESCRIPTION
**Pull request by citizenmatt**
Addresses major performance issues with large numbers of large YAML files.

Memory usage:
- [x] Use text buffers instead of allocating strings for each node in the PSI tree
- [x] Use chameleon nodes to skip creating PSI sub-trees for documents that don't need to be examined

Solution load performance:
- [x] Don't walk entire PSI tree looking for references in `UnityEvent` handler cache

Find usages performance:
- [x] Don't walk entire PSI tree looking for references in standard YAML reference searcher

### CODE REVIEW

**Comment by SugoiDev** [comment]
Could you consider adding #914 as part of this change?

**Comment by citizenmatt** [comment]
Short answer is no. I’ll reply over there with a longer answer when I’m not on my phone :)

**Comment by citizenmatt** [comment]
And it’s not as bad as it sounds!

**Comment by SugoiDev** [comment]
No problem, take your time!

**Pull request merged**
