### PR TITLE
Show in unity fix for `package@version` in path

### PR DESCRIPTION
**Pull request by van800**
see https://github.com/JetBrains/resharper-unity/pull/2124#issuecomment-890868130

Planned for backport to 212.

### CODE REVIEW

**Comment by citizenmatt** [comment]
We have all the information to know if a file is part of a package. Would it help if we could get `package@version` to provide a project-relative path that would work with the asset DB without having to load everything?

**Comment by van800** [comment]
We have to load it anyway to highlight in Unity Editor.

**Comment by citizenmatt** [comment]
Sorry, I meant we could construct the `package@version` path so we could avoid calling `GetAllAssetPaths` and do a string comparison for each path.

**Comment by van800** [comment]
Yes, I see what you mean now. I should do a measurement on a really big solution, to see, if we need such optimisation.

**Pull request merged**
