### PR TITLE
Compare API versions ignoring missing build numbers

### PR DESCRIPTION
**Pull request by citizenmatt**
Rider 2020.2 updated API information for `ScriptableObject.OnValidate`. It is undocumented up to Unity 2020.1, and documented from Unity 2020.2. The implementation of `Version.CompareTo` will treat missing build and revision numbers as older, so a maximum API version of 2020.1 is less than the product version of 2020.1.1, and since this is also less than 2020.2, Rider does not find a record for `ScriptableObject.OnValidate`.

This change introduces an extension method for `Version` - `CompareToLenient`. This will only compare the components of both versions that are defined, so `2020.1` is considered equal to `2020.1.1`. This fixes the issue for `ScriptableObject.OnValidate`.

Fixes [RIDER-49130](https://youtrack.jetbrains.com/issue/RIDER-49130)

### CODE REVIEW

**Comment by citizenmatt** [comment]
I don't see it documented for [2018.4](https://docs.unity3d.com/2018.4/Documentation/ScriptReference/ScriptableObject.html) or [2019.4](https://docs.unity3d.com/2019.4/Documentation/ScriptReference/ScriptableObject.html). But it is documented for [2020.1](https://docs.unity3d.com/2020.1/Documentation/ScriptReference/ScriptableObject.html). I'll update the specs for 2020.1. It's still listed for earlier versions, but marked as undocumented.

**Comment by tbg10101** [comment]
Sorry, my comment was for MonoBehaviour.

**Comment by citizenmatt** [comment]
`MonoBehaviour.OnValidate` is already supported.

Screenshot 2020-08-24 at 3 21 27 pm

**Comment by tbg10101** [comment]
You are right, I don't know what I was thinking. Sorry for the churn.

**Comment by citizenmatt** [comment]
No worries 😄

**Review by krasnotsvetov — APPROVED** [review]

**Pull request merged**
