### PR TITLE
Implemented assembly locking

### PR DESCRIPTION
**Pull request by JurjenBiewenga**
This fixes issue #520

### CODE REVIEW

**Comment by van800** [comment]
Hi! 
EditorGUILayout.Popup would be better UX than just Toggle. Consider the following:
"Compile during Play"
 - "Immediate"
 - "Manual"
We may later add something like "Compile on Stop", "Stop and Recompile" options.

**Comment by JurjenBiewenga** [comment]
Hey, thanks for the feedback.
I'll change it around to popup and I'll add stop and recompile as well.

**Comment by van800** [comment]
Hey! I finally had time for review.
Few problems here.
1. It all doesn't work when there is no Rider protocol connection. Just leave Unity and close Rider - 
riderProtocolController.Wire.Connected.WhenTrue will never fire.
2. New names are not self-explanatory. But don't focus on that much, we can change them later.
3. Doing constant checks on       EditorApplication.update += () =>
is not a good idea, I guess.
Try using  AppDomain.CurrentDomain.DomainUnload += (sender, args) =>
instead.

**Comment by IvanPashchenko** [comment]
@JurjenBiewenga hey, thanks for the PR!

Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.

@citizenmatt we should probably say something about CLA in the `readme.md`. Or set up an `contributors.md`.

**Comment by van800** [comment]
Oh man, I am a bit sad for the time we have spent on this. Occasionally I found out that exactly same feature was added by Unity team in Unity 2018.2. 
image

**Comment by JurjenBiewenga** [comment]
Arguably it would still be a good feature as a lot of users are stuck on the 2017 or even the 5.x versions of Unity.

**Comment by van800** [comment]
I did some testing, everything seems working.
I added two tiny finish changes in branch
https://github.com/JetBrains/resharper-unity/commits/pr-609
If @JurjenBiewenga you agree, I will merge it.

**Comment by JurjenBiewenga** [comment]
Thanks for the changes. Feel free to merge it.

**Pull request closed without merging**
