### PR TITLE
Avoid waiting for full solution opening for installing Editor Plugin

### PR DESCRIPTION
**Pull request by van800**
refer to https://github.com/JetBrains/resharper-unity/blob/183/resharper/src/resharper-unity/ProjectModel/UnitySolutionTracker.cs

https://github.com/JetBrains/resharper-unity/issues/581

### CODE REVIEW

**Comment by korifey** [comment]
Do you recalculate property each time any of 3 directories updated? Is this the purpose?

**Comment by van800** [comment]
Created or deleted, yes

**Comment by IvanPashchenko** [comment]
@van800 If `UnityReferencesTracker` and `UnresolvedUnityReferencesTracker` are not used anymore, please remove them

**Comment by van800** [comment]
> @van800 If `UnityReferencesTracker` and `UnresolvedUnityReferencesTracker` are not used anymore, please remove them

still used.

**Pull request merged**
